export interface Checkvehiculos{
	id?: number;
	fecha:string;
    folio:number;
    num_trabajador: number;
    vehiculo:string;
    placas:string;
    kilometraje:string;
    no_poliza:string;
    folio_t_circul:string;
    vigencia_seguro:string;
    vehiculo_presenta:string;
    v_pdescripcion:string;
    luces:string;
    espejo_laterales:string;
    cristales:string;
    parabrisas:string;
    llantas:string;
    tapon_ruedas:string;
    molduras_complet:string;
    tapon_combustible:string;
    carroceria_s_golpes:string;
    cable_pasa_corri:string;
    calzas:string;
    faros_reverseros:string;
    estado_neumaticos:string;
    alarma_reversa:string;
    claxon:string;
    instrum_tablero:string;
    calefaccion:string;
    limpia_parabrisas:string;
    torreta:string;
    encendedor:string;
    espejo_retrovisor:string;
    cinturon_seguridad:string;
    conos_t_seguridad:string;
    botones_interiores:string;
    manijas_interiores:string;
    tapetes:string;
    vestiduras:string;
    tarjeta_circulacion:string;
    poliza_seguro:string;
    aire_acondicionado:string;
    gato_hidraulico:string;
    maneral_gato:string;
    llave_cruz:string;
    estuche_herramient:string;
    llanta_refaccion:string;
    extintor:string;
    tapon_aceite:string;
    antenas_radio:string;
    tapon_radiador:string;
    bayoneta:string;
    radio:string;
    bateria:string;
    botiquin:string;
    limpieza_general:string;
    bitacora_mant:string;
    cantidad_combusti:string;
    nombre_conductor:string;
    numero_licencia:string;
    tipo_licencia:string;
    vigencia_licencia:string;
    licencia_int_vig:string;
    estado_lic_inter:string;
    coment_adicionales:string;
    trab_r_checklist:string;
    nombre_supervisor:string;
    revisado_valido?:string;
    created_at?: string;
    update_at?: string;


}